- name: My first play
  hosts: myhosts
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world

   - name: Show OS version
     ansible.builtin.debug:
       var: ansible_facts['distribution']

   - name: Only run on Debian-like systems
     ansible.builtin.debug:
       msg: "Debian system detected.:"
     when: ansible_facts['os_family'] == "Debian"

